import { School } from '@prisma/client'

export const schools = [
  {
    name: 'San Jose State University',
    location: 'San Jose, CA',
    description:
      'San José State University is a public university in San Jose, California. Established in 1857, SJSU is the oldest public university on the West Coast and the founding campus of the California State University system.',
    founded: 1857,
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/ec/San_Jose_State_Spartans_logo.svg',
    emailDomain: 'sjsu.edu',
    numUsers: 0,
  },
  {
    name: 'Stanford University',
    location: 'Stanford, CA',
    description:
      'Stanford University is a private research university in Stanford, California, United States. It was founded in 1885 by railroad magnate Leland Stanford, the eighth governor of and then-incumbent senator from California, and his wife, Jane, in memory of their only child, Leland Jr.',
    founded: 1885,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Stanford_Cardinal_logo.svg/800px-Stanford_Cardinal_logo.svg.png',
    emailDomain: 'stanford.edu',
    numUsers: 0,
  },
  {
    name: 'University of California, Berkeley',
    location: 'Berkeley, CA',
    description:
      "The University of California, Berkeley is a public land-grant research university in Berkeley, California, United States. Founded in 1868 and named after the Anglo-Irish philosopher George Berkeley, it is the state's first land-grant university and is the founding campus of the University of California system. ",
    founded: 1868,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Seal_of_University_of_California%2C_Berkeley.svg',
    emailDomain: 'berkeley.edu',
    numUsers: 0,
  },
] as School[]

// large list of common first names
export const firstNames = [
  'James',
  'John',
  'Robert',
  'Michael',
  'William',
  'David',
  'Richard',
  'Joseph',
  'Charles',
  'Thomas',
  'Christopher',
  'Daniel',
  'Matthew',
  'Anthony',
  'Mark',
  'Donald',
  'Steven',
  'Paul',
  'Andrew',
  'Joshua',
  'Kenneth',
  'Kevin',
  'Brian',
  'George',
  'Edward',
  'Ronald',
  'Timothy',
  'Jason',
  'Jeffrey',
  'Ryan',
  'Jacob',
  'Gary',
  'Nicholas',
  'Eric',
  'Stephen',
  'Jonathan',
  'Larry',
  'Justin',
  'Scott',
  'Brandon',
  'Frank',
  'Benjamin',
  'Gregory',
  'Samuel',
  'Raymond',
  'Patrick',
  'Alexander',
  'Jack',
  'Dennis',
  'Jerry',
  'Tyler',
  'Aaron',
  'Jose',
  'Henry',
  'Adam',
  'Douglas',
  'Nathan',
  'Peter',
  'Zachary',
  'Kyle',
  'Walter',
  'Harold',
  'Jeremy',
  'Ethan',
  'Carl',
  'Keith',
  'Roger',
  'Gerald',
  'Vincent',
  'Arthur',
  'Terry',
  'Sean',
  'Christian',
  'Roy',
  'Willie',
  'Austin',
  'Bruce',
  'Eugene',
  'Louis',
  'Harry',
  'Randy',
  'Howard',
  'Bobby',
  'Victor',
  'Martin',
  'Ernest',
  'Phillip',
  'Todd',
  'Jesse',
  'Craig',
  'Alan',
  'Shawn',
  'Clarence',
  'Sean',
  'Philip',
  'Chris',
  'Johnny',
  'Earl',
  'Jimmy',
  'Antonio',
  'Danny',
  'Bryan',
  'Tony',
  'Luis',
  'Mike',
  'Stanley',
  'Leonard',
  'Nathan',
  'Dale',
  'Manuel',
  'Rodney',
  'Curtis',
  'Norman',
] as const

export const lastNames = [
  'Smith',
  'Johnson',
  'Williams',
  'Jones',
  'Brown',
  'Davis',
  'Miller',
  'Wilson',
  'Moore',
  'Taylor',
  'Anderson',
  'Thomas',
  'Jackson',
  'White',
  'Harris',
  'Martin',
  'Thompson',
  'Garcia',
  'Martinez',
  'Robinson',
  'Clark',
  'Rodriguez',
  'Lewis',
  'Lee',
  'Walker',
  'Hall',
  'Allen',
  'Young',
  'Hernandez',
  'King',
  'Wright',
  'Lopez',
  'Hill',
  'Scott',
  'Green',
  'Adams',
  'Baker',
  'Gonzalez',
  'Nelson',
  'Carter',
  'Mitchell',
  'Perez',
  'Roberts',
  'Turner',
  'Phillips',
  'Campbell',
  'Parker',
  'Evans',
  'Edwards',
  'Collins',
  'Stewart',
  'Sanchez',
  'Morris',
  'Rogers',
  'Reed',
  'Cook',
  'Morgan',
  'Bell',
  'Murphy',
  'Bailey',
  'Rivera',
  'Cooper',
  'Richardson',
  'Cox',
  'Howard',
  'Ward',
  'Torres',
  'Peterson',
  'Gray',
  'Ramirez',
  'James',
  'Watson',
  'Brooks',
  'Kelly',
  'Sanders',
  'Price',
  'Bennett',
  'Wood',
  'Barnes',
  'Ross',
  'Henderson',
  'Coleman',
  'Jenkins',
  'Perry',
  'Powell',
  'Long',
  'Patterson',
  'Hughes',
  'Flores',
  'Washington',
  'Butler',
  'Simmons',
  'Foster',
  'Gonzales',
  'Bryant',
  'Alexander',
  'Russell',
  'Griffin',
  'Diaz',
  'Hayes',
] as const

export const bios = [
  'Passionate about art and exploring digital illustration. Loves binge-watching documentaries and discovering indie music. Weekend painter and coffee enthusiast.',
  'Aspiring chef who loves experimenting with recipes and food photography. Enjoys late-night board game sessions with friends and frequenting local thrift shops.',
  'Eco-conscious student deeply involved in sustainability initiatives. Loves hiking, tending to her indoor plant collection, and exploring zero-waste living.',
  'Film buff with a love for classic cinema and filmmaking. Often found at indie theaters or writing scripts in cozy cafes. Dreams of traveling across Europe someday.',
  'Bookworm and aspiring novelist who loves writing poetry. Enjoys organizing book club meetings and hunting for rare books in secondhand shops.',
  'Big on gaming and tech – often tinkering with hardware and coding small projects. Loves sci-fi novels and listening to gaming soundtracks while studying.',
  'Nature lover who spends weekends exploring trails and birdwatching. Enjoys gardening and DIY crafting, with a particular interest in eco-friendly projects.',
  'Movie critic among friends with a talent for recommending hidden gems. Enjoys baking desserts, journaling, and making playlists for every mood.',
  'Volunteer at the local animal shelter. Passionate about animal welfare and DIY crafting. Loves learning about pet care and cozying up with mystery novels.',
  'Tech enthusiast working on personal coding projects and exploring VR. Enjoys late-night coding sessions, retro games, and building robots on weekends.',
  'Self-taught guitarist who loves classic rock and experimenting with music production. Enjoys going to open mic nights and discovering new artists.',
  'Passionate about sustainable fashion and DIY projects. Loves thrifting, upcycling old clothes, and hosting themed movie nights with friends.',
  'Amateur photographer who loves capturing urban landscapes. Enjoys editing photos, exploring new parts of the city, and discovering hidden cafes.',
  'Keen on learning about mythology and folklore from different cultures. Loves reading fantasy novels, writing short stories, and attending book fairs.',
  'Plant parent with a growing collection of succulents and cacti. Loves crafting and spending weekends at the farmer’s market hunting for unique plants.',
  'Poetry lover who organizes open mic nights and loves spoken word. Enjoys painting abstract art, discovering new coffee spots, and baking sourdough.',
  'Podcast enthusiast, often listening to true crime or science shows. Loves experimenting with different art mediums and visiting art installations.',
  'Part-time barista and coffee enthusiast. Passionate about learning latte art, creating new coffee recipes, and hosting coffee tastings with friends.',
  'Avid photographer who’s rarely seen without a camera. Loves capturing candid moments, editing photos, and exploring vintage cameras.',
  'Collector of vinyl records and classic books. Loves hosting book exchanges, discovering jazz music, and baking for friends on weekends.',
  'Creative writer with a love for flash fiction and surrealist poetry. Enjoys illustrating her stories and attending small local art exhibits.',
  'History buff who spends weekends volunteering at the museum. Loves journaling, researching local folklore, and uncovering historical landmarks.',
  'Frequent visitor of farmers’ markets and antique shops. Loves finding unique ingredients, trying new recipes, and blogging about sustainable living.',
  'Budding photographer with a passion for street photography and cityscapes. Enjoys journaling, watching indie films, and visiting art museums.',
  'Podcaster who shares thoughts on mental health and self-growth. Loves editing audio, journaling, and engaging in online communities.',
  'Amateur baker specializing in vegan treats. Loves experimenting with new recipes, organizing study groups, and volunteering at community events.',
  'Big into DIY crafts and home decor. Loves upcycling thrift finds, hosting movie marathons, and blogging about her creative projects.',
  'Self-taught graphic designer passionate about creating digital art. Loves browsing art exhibitions, collecting quirky stickers, and journaling.',
  'Fan of true crime and mystery novels. Loves exploring abandoned places, journaling about adventures, and planning elaborate themed parties.',
  'Hobbyist baker who loves making cupcakes and desserts for friends. Enjoys discovering new music, reading horror novels, and writing short stories.',
  'Plant enthusiast with a windowsill full of succulents. Loves experimenting with new recipes, thrifting, and trying to perfect her iced coffee skills.',
  'DIY craft enthusiast who loves making handmade gifts. Enjoys upcycling old furniture, watching historical documentaries, and exploring nature.',
  'Podcast junkie with a love for self-improvement and science shows. Loves painting, curating playlists for friends, and experimenting with new recipes.',
  'Always sketching and dreaming up new comic ideas. Loves going to comic shops, exploring online art communities, and trying new digital art tools.',
  'Sewing enthusiast who loves making custom clothes. Enjoys thrifting, collecting vintage fashion magazines, and blogging about sustainable style.',
  'Part-time photographer passionate about portrait photography. Loves photo editing, organizing creative meetups, and exploring digital art.',
  'Journalist at heart, loves covering campus stories and reading investigative journalism. Enjoys thrifting, finding rare records, and painting landscapes.',
  'Amateur poet who loves attending open mic nights and reading fantasy novels. Enjoys journaling, collecting unique pens, and visiting art fairs.',
  'Food lover who’s always hunting for the best local spots. Enjoys learning about food history, journaling about culinary adventures, and cooking.',
  'Film photographer who loves capturing candid moments. Enjoys making playlists, exploring bookstores, and spending hours in photo editing.',
  'Minimalist enthusiast who blogs about mindful living and organization. Loves bullet journaling, experimenting with vegan recipes, and candle making.',
  'True crime podcast fanatic who’s into criminology and psychology. Enjoys journaling, watching documentaries, and planning road trips with friends.',
  'Amateur chef experimenting with fusion dishes and food styling. Loves taking cooking classes, exploring food markets, and hosting potluck dinners.',
  'Thrill-seeker who loves horror movies and exploring urban legends. Enjoys reading fantasy novels, journaling, and visiting themed cafes.',
  'Music producer and aspiring DJ. Loves mixing electronic beats, designing album covers, and discussing music theory with fellow artists.',
  'Vintage enthusiast who collects old postcards and decor. Enjoys crafting handmade jewelry, exploring flea markets, and baking for friends.',
  'Indie music enthusiast who’s always hunting for underground bands. Enjoys curating playlists, attending local gigs, and collecting vinyl records.',
  'Big on sustainable fashion, with a closet full of thrift finds. Loves experimenting with DIY fashion, eco-friendly projects, and vintage shopping.',
  'True-crime buff who loves solving puzzles and watching mysteries. Enjoys cooking for friends, collecting mystery novels, and visiting escape rooms.',
  'Language learner with an interest in different cultures. Enjoys studying languages, collecting postcards, and cooking dishes from around the world.',
  'Comic book fan and aspiring graphic novelist. Loves designing characters, binge-reading comics, and attending local comic conventions.',
] as const

export const majors = [
  'Computer Science',
  'Business Administration',
  'Psychology',
  'Biology',
  'Nursing',
  'Engineering',
  'Political Science',
  'Economics',
  'English',
  'History',
  'Sociology',
  'Mathematics',
  'Chemistry',
  'Art',
  'Music',
  'Physics',
  'Philosophy',
  'Communications',
  'Anthropology',
  'Theater',
  'Education',
  'Geology',
  'Environmental Science',
  'Criminal Justice',
  'Journalism',
  'Marketing',
  'Graphic Design',
  'Public Health',
  'Nutrition',
  'Film Studies',
  'Linguistics',
  'Agriculture',
  'Astronomy',
  'Dance',
  'Fashion Design',
  'Interior Design',
  'Urban Planning',
  'Social Work',
  'International Relations',
  'Religious Studies',
  'Sports Management',
  'Forensic Science',
  'Software Engineering',
] as const

export const sports = [
  'Badminton',
  'Baseball',
  'Basketball',
  'Cricket',
  'FlagFootball',
  'Frisbee',
  'Golf',
  'PickleBall',
  'Running',
  'Soccer',
  'Softball',
  'Swimming',
  'TableTennis',
  'Tennis',
  'Volleyball',
] as const

export const schoolYear = [
  'Freshman',
  'Sophomore',
  'Junior',
  'Senior',
  'Graduate',
] as const
